# Generated by Django 6.0.6 on 2026-06-08 20:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, validators=[django.core.validators.MinLengthValidator(2)])),
                ('description', models.TextField()),
                ('vote_count', models.IntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ideas_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-vote_count', '-created_at'],
                'indexes': [models.Index(fields=['-vote_count', '-created_at'], name='idea_idea_vote_co_0eb420_idx'), models.Index(fields=['created_by'], name='idea_idea_created_e8d6af_idx')],
            },
        ),
    ]
