# Generated by Django 6.0.6 on 2026-06-09 11:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0002_alter_idea_vote_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='vote_count',
            field=models.IntegerField(db_index=True, default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
